# yaml file for protocol templates
# This is a simple way to bootstrap the data base. 
# The structure will pull from the a live protocol database if one exists.
# I am keeping this pretty minimal because it should also be able to be updated
# Using a specific manifest hash.

creator: "Homunculus Pat"
created_on: "2026-08-21"
pipelines:
    CryPrep_biomek_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {"A":["B","C"],"B":"D","C":"D"}
        protocol_titles : {"A":"my first cool protocol","B":"second","C":"Third","D":"and the output"}

    FFPE_digestion_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {}
        protocol_titles: {}

    In_gel_digestion_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {}
        protocol_titles: {}

    IP_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {}
        protocol_titles: {}

    IPMS_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {}
        protocol_titles: {}

    FF_SDS_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {}
        protocol_titles: {}

    Frozen_tissue_base:
        version_id : 0
        pipeline_guid:  null
        manifest_hash : null
        root: null
        executoror: null
        protocol_dag : {}
        protocol_titles: {}
